services:

  nodo-master:
    image: hadoop-cluster:3.4.3
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodo-master
    hostname: nodo-master
    command: ["/scripts/start-master.sh"]

    ports:
      # Interfaz web del NameNode
      - "9870:9870"

      # Interfaz web de YARN
      - "8088:8088"

      # Comunicación HDFS
      - "9000:9000"

      # Interfaz del SecondaryNameNode
      - "9868:9868"

      # Interfaz temporal de Spark
      - "4040:4040"
    
    expose:
      - "5000"

    volumes:
      - namenode_data:/data/hdfs/namenode
      - ./laboratorio2:/laboratorio2:ro
      - ./laboratorio3:/laboratorio3

    networks:
      - hadoop-network

    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:9870/ > /dev/null"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 20s

    stop_grace_period: 30s

  nodo-slave1:
    image: hadoop-cluster:3.4.3
    container_name: nodo-slave1
    hostname: nodo-slave1
    command: ["/scripts/start-worker.sh"]

    ports:
      # Interfaz web del DataNode 1
      - "9864:9864"

      # Interfaz web del NodeManager 1
      - "8042:8042"

    expose:
      - "5001"

    volumes:
      - datanode1_data:/data/hdfs/datanode
      - ./laboratorio2:/laboratorio2:ro
      - ./laboratorio3:/laboratorio3

    networks:
      - hadoop-network

    depends_on:
      nodo-master:
        condition: service_healthy

    stop_grace_period: 30s

  nodo-slave2:
    image: hadoop-cluster:3.4.3
    container_name: nodo-slave2
    hostname: nodo-slave2
    command: ["/scripts/start-worker.sh"]

    ports:
      # El puerto externo cambia para evitar conflictos
      - "9865:9864"
      - "8043:8042"
    
    expose:
      - "5002"

    volumes:
      - datanode2_data:/data/hdfs/datanode
      - ./laboratorio2:/laboratorio2:ro
      - ./laboratorio3:/laboratorio3
      
    networks:
      - hadoop-network

    depends_on:
      nodo-master:
        condition: service_healthy

    stop_grace_period: 30s

  redis-memoria:
    image: redis:7.4.10-alpine
    container_name: redis-memoria
    hostname: redis-memoria

    command:
      - redis-server
      - --bind
      - 0.0.0.0
      - --protected-mode
      - "no"
      - --appendonly
      - "yes"

    volumes:
      - redis_data:/data

    networks:
      - hadoop-network

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

networks:
  hadoop-network:
    name: hadoop-network
    driver: bridge

volumes:
  namenode_data:
    name: hadoop-namenode-data

  datanode1_data:
    name: hadoop-datanode1-data

  datanode2_data:
    name: hadoop-datanode2-data

  redis_data:
    name: redis-memoria-data