# Ejecutar Spark utilizando YARN
spark.master                     yarn
spark.submit.deployMode          client
spark.yarn.queue                 default
spark.yarn.maxAppAttempts        1

# Dos ejecutores: uno por cada nodo trabajador
spark.executor.instances         2
spark.executor.cores             1
spark.executor.memory            512m
spark.executor.memoryOverhead    128m

# Recursos del ApplicationMaster
spark.yarn.am.memory             512m
spark.yarn.am.memoryOverhead     128m

# Driver ejecutado desde nodo-master
spark.driver.memory              512m
spark.driver.host                nodo-master
spark.driver.bindAddress         0.0.0.0
spark.driver.port                7078
spark.blockManager.port          7079

# Configuración de Python
spark.pyspark.python             python3
spark.pyspark.driver.python      python3

# Paralelismo del laboratorio
spark.default.parallelism        2

# Directorios y monitoreo
spark.local.dir                  /tmp/spark
spark.ui.enabled                 true
spark.ui.port                    4040